local Msg = require("lib.msg")
local Entity = require("utils.entity")

local Urls = {
	Body = "#body",
	BodyTrigger = "#body_trigger",
	GameController = "/controller#controller",
}

go.property("door_option", 1)

local function on_hide_element(self, message)
	Entity.disable_body(Urls.Body)
end

local function on_trigger_response(self, message)
	pprint("on_trigger_response", message)
	if not message.own_group == "wall_trigger" then return end
	if not message.enter then return end

	pprint("door_entered", message)

	msg.post(Urls.GameController, Msg.Stager.DOOR_ENTERED, {
		door_option = self.door_option,
	})
end

function on_message(self, message_id, message, sender)
	if message_id == Msg.HIDE_ELEMENT then
		on_hide_element(self, message)
	elseif message_id == Msg.TRIGGER_OCCURRED then
		on_trigger_response(self, message)
	end
end
