local Msg = require("lib.msg")
local Entity = require("utils.entity")

local Urls = {
	Body = "#body",
	BodyTrigger = "#body_trigger",
	GameController = "/controller",
}

go.property("next_stage", hash("none"))
go.property("reward", hash("none"))

function init(self)
	self.used = false
	-- TODO: self.reward for icon
end

local function on_hide_element(self, message)
	Entity.disable_body(Urls.Body)
end

local function on_trigger_response(self, message)
	if self.used then return end
	if message.own_group ~= hash("wall_trigger") then return end
	if not message.enter then return end

	self.used = true
	Entity.disable_body(Urls.Body)
	msg.post(Urls.GameController, Msg.Stager.CONNECTION_ENTERED, {
		next_stage = self.next_stage,
	})
end

function on_message(self, message_id, message, sender)
	if message_id == Msg.HIDE_ELEMENT then
		on_hide_element(self, message)
	elseif message_id == Msg.TRIGGER_OCCURRED then
		on_trigger_response(self, message)
	end
end
