local Msg = require("lib.msg")
local Input = require("lib.inputs")
local Pooler = require("utils.pooler")

local Urls = {
	Factories = {
		Perrocoin = "/factories#perrocoin_cfactory",
		Stage_01 = "/stages_factory#stage_01_factory",
		VendingMachine = "/factories#vending_factory",
	},
	-- External
	UIController = "/ui",
	Player = "/player/root",
	MainController = "main:/main_controller",
	SoundController = "/sound_controller",
}

local StatesEnum = {
	Active = 1,
	Paused = 2,
	AutoCollect = 3,
}

local function _spawn_perrocoin(self, options)
	local properties = options and options.value and { value = options.value } or nil
	local position = options and options.position or vmath.vector3()

	local new_collection = collectionfactory.create(Urls.Factories.Perrocoin, position, nil, properties)
	return new_collection["/root"]
end

function init(self)
	msg.post(".", "acquire_input_focus")
	self.current_stage = collectionfactory.create(Urls.Factories.Stage_01)
	self.pool_perrocoin = Pooler.new({
		pool_size = 10,
		spawner = _spawn_perrocoin,
	})

	self.state = StatesEnum.Active
end

local function on_set_life_count(self, message)
	self.player_life_count = message.lives
	msg.post(Urls.UIController, Msg.UI.SET_LIFE_NODES, {
		lives = self.player_life_count,
	})
end

local function on_player_life_changed(self, message)
	self._current_player_life_count = message.current_lives

	msg.post(Urls.UIController, Msg.UI.LIFE_CHANGED, message)
	if self._current_player_life_count == 0 then
		msg.post(Urls.MainController, hash("game_over"))
		return
	end
end

local function on_enemy_killed(self, message)
	msg.post(self.current_stage["/root"], Msg.Stager.ENEMY_KILLED, message)

	-- spawn cogs points
	local random_perrocoins = math.random(0, 2)
	if random_perrocoins > 0 then
		for i = 1, random_perrocoins do
			local perrocoin_id = self.pool_perrocoin:pull()
			if not perrocoin_id then
				perrocoin_id = self.pool_perrocoin:extend()
			end

			msg.post(perrocoin_id, Msg.SHOW_ELEMENT, {
				position = message.position,
			})
		end
	end
end

local function on_door_entered(self, message)
	msg.post(Urls.UIController, Msg.UI.SHOW_WIPE)
end

local function on_perrocoin_picked(self, message)
	self.pool_perrocoin:push_item(message.perrocoin_id)
end

local function on_perrocoin_expired(self, message)
	self.pool_perrocoin:push_item(message.perrocoin_id)
end

local TIME_TO_SHOW_SHOP_MODAL = 0.3
local TIME_TO_AUTO_COLLECT_POINT = TIME_TO_SHOW_SHOP_MODAL / 2
local function on_open_vending(self, message)
	msg.post(Urls.UIController, Msg.UI.DISABLE_BUTTON_ACTION)
	msg.post(Urls.UIController, Msg.UI.DISABLE_MOVE)
	msg.post(Urls.Player, Msg.Player.MOVE_RELEASED)

	local pending_perrocoins = self.pool_perrocoin.in_use
	if #pending_perrocoins > 0 then
		for _, perrocoin_id in ipairs(pending_perrocoins) do
			-- TODO: refactor this
			msg.post(perrocoin_id, Msg.Game.AUTO_COLLECT_POINT, {
				target = go.get_id(Urls.Player),
				time = TIME_TO_AUTO_COLLECT_POINT,
			})
		end

		local upgrade_type = message.upgrade_type
		timer.delay(TIME_TO_SHOW_SHOP_MODAL, false, function()
			msg.post(Urls.UIController, Msg.UI.SHOW_SHOP_MODAL, { upgrade_type = upgrade_type })
		end)

		return
	end

	msg.post(Urls.UIController, Msg.UI.SHOW_SHOP_MODAL, { upgrade_type = message.upgrade_type })
end

local function on_spawn_vending(self, message)
	self.vending_id = factory.create(Urls.Factories.VendingMachine, message.position, nil, {
		upgrade_type = message.upgrade_type,
	})
end

local function on_upgrade_chosen(self, message)
	if not self.vending_id then return end

	msg.post(self.vending_id, Msg.Vending.DISAPPEAR)
	self.vending_id = nil
end

function on_message(self, message_id, message, sender)
	if message_id == Msg.Game.PLAYER_SET_LIFE_COUNT then
		on_set_life_count(self, message)
	elseif message_id == Msg.Game.PLAYER_LIFE_CHANGED then
		on_player_life_changed(self, message)
	elseif message_id == Msg.Stager.ENEMY_KILLED then
		on_enemy_killed(self, message)
	elseif message_id == Msg.Stager.ENTER_DOOR then
		on_door_entered(self, message)
	elseif message_id == Msg.Game.PERROCOIN_PICKED then
		on_perrocoin_picked(self, message)
	elseif message_id == Msg.Game.PERROCOIN_EXPIRED then
		on_perrocoin_expired(self, message)
	elseif message_id == Msg.Game.OPEN_VENDING then
		on_open_vending(self, message)
	elseif message_id == Msg.Stager.SPAWN_VENDING then
		on_spawn_vending(self, message)
	elseif message_id == Msg.Game.UPGRADE_CHOSEN then
		on_upgrade_chosen(self, message)
	end
end

---@package
---@param self game_controller.script
---@param action_id hash
---@param action on_input.action
---@return boolean|nil
function on_input(self, action_id, action)
	if action_id == Input.Profile and action.pressed then
		msg.post("@system:", "toggle_profile")
	elseif action_id == Input.Physics and action.pressed then
		msg.post("@system:", "toggle_physics_debug")
	end
end
