local Msg = require("lib.msg")

local Urls = {
	UIController = "/ui",
	MainController = "main:/main_controller",
	Factories = {
		Stage_01 = "/stages_factory#stage_01_factory"
	}
}

function init(self)
	self.current_stage = collectionfactory.create(Urls.Factories.Stage_01)
end

local function on_set_life_count(self, message)
	self.player_life_count = message.lives
	msg.post(Urls.UIController, Msg.Game.PLAYER_SET_LIFE_COUNT, {
		lives = self.player_life_count,
	})
end

local function on_player_life_changed(self, message)
	self._current_player_life_count = message.current_lives

	msg.post(Urls.UIController, Msg.Game.PLAYER_LIFE_CHANGED, message)
	if self._current_player_life_count == 0 then
		msg.post(Urls.MainController, hash("game_over"))
		return
	end
end

local function on_enemy_killed(self, message)
	msg.post(self.current_stage["/root"], Msg.Stager.ENEMY_KILLED, message)
end

local function on_door_entered(self, message)
	msg.post(Urls.UIController, Msg.Game.SHOW_WIPE)
end

function on_message(self, message_id, message, sender)
	if message_id == Msg.Game.PLAYER_SET_LIFE_COUNT then
		on_set_life_count(self, message)
	elseif message_id == Msg.Game.PLAYER_LIFE_CHANGED then
		on_player_life_changed(self, message)
	elseif message_id == Msg.Stager.ENEMY_KILLED then
		on_enemy_killed(self, message)
	elseif message_id == Msg.Stager.ENTER_DOOR then
		on_door_entered(self, message)
	end
end
