local Msg = require("lib.msg")
local Pooler = require("utils.pooler")

local Urls = {
	Factories = {
		Perrocoin = "/factories#perrocoin_cfactory",
	},
	-- External
	UIController = "/ui",
	Player = "/player/root",
	SoundController = "/sound_controller",
}

local StatesEnum = {
	Active = 1,
	Paused = 2,
	AutoCollect = 3,
}

local function _spawn_perrocoin(self, options)
	local properties = options and options.value and { value = options.value } or nil
	local position = options and options.position or vmath.vector3()

	local new_collection = collectionfactory.create(Urls.Factories.Perrocoin, position, nil, properties)
	return new_collection["/root"]
end

function init(self)
	self.pool_perrocoin = Pooler.new({
		pool_size = 10,
		spawner = _spawn_perrocoin,
	})

	self.state = StatesEnum.Active
end

local function on_enemy_killed(self, message)
	-- spawn cogs points
	local random_perrocoins = math.random(0, 2)
	if random_perrocoins > 0 then
		for i = 1, random_perrocoins do
			local perrocoin_id = self.pool_perrocoin:pull()
			if not perrocoin_id then
				perrocoin_id = self.pool_perrocoin:extend()
			end

			msg.post(perrocoin_id, Msg.SHOW_ELEMENT, {
				position = message.position,
			})
		end
	end
end

local function on_door_entered(self, message)
	msg.post(Urls.UIController, Msg.UI.SHOW_WIPE)
end

local function on_perrocoin_picked(self, message)
	self.pool_perrocoin:push_item(message.perrocoin_id)
end

local function on_perrocoin_expired(self, message)
	self.pool_perrocoin:push_item(message.perrocoin_id)
end

local TIME_TO_SHOW_SHOP_MODAL = 0.3
local TIME_TO_AUTO_COLLECT_POINT = TIME_TO_SHOW_SHOP_MODAL / 2
local function on_open_upgrader(self, message)
	-- msg.post(Urls.UIController, Msg.UI.DISABLE_BUTTON_ACTION)
	-- msg.post(Urls.UIController, Msg.UI.DISABLE_MOVE)
	msg.post(Urls.Player, Msg.Player.MOVE_RELEASED)
	msg.post(Urls.UIController, Msg.UI.SHOW_SHOP_MODAL, message)
end

function on_message(self, message_id, message, sender)
	if message_id == Msg.Enemy.ENEMY_KILLED then
		on_enemy_killed(self, message)
	elseif message_id == Msg.Stager.DOOR_ENTERED then
		on_door_entered(self, message)
	elseif message_id == Msg.Game.PERROCOIN_PICKED then
		on_perrocoin_picked(self, message)
	elseif message_id == Msg.Game.PERROCOIN_EXPIRED then
		on_perrocoin_expired(self, message)
	elseif message_id == Msg.Game.OPEN_UPGRADER then
		on_open_upgrader(self, message)
	end
end
