local Msg = require("lib.msg")

local Urls = {
	UIController = "/ui",
	MainController = "main:/main_controller",
}

function init(self)
	self.run_ended = false
	self.player_life_count = 0
end

local function on_player_life_initialized(self, message)
	self.player_life_count = message.lives
	msg.post(Urls.UIController, Msg.HudUI.SET_LIFE_PROGRESS, {
		total_lives = self.player_life_count,
	})
end

local function on_player_life_changed(self, message)
	msg.post(Urls.UIController, Msg.HudUI.CHANGE_LIFE_PROGRESS, message)

	if message.current_lives <= 0 and not self.run_ended then
		self.run_ended = true
		msg.post(Urls.MainController, Msg.Main.GAME_OVER)
	end
end

local function on_player_special_action_used(self, message)
	if message.is_active then return end

	msg.post(Urls.UIController, Msg.ControlsUI.DISABLE_BUTTON_ACTION)
end

function on_message(self, message_id, message, sender)
	if message_id == Msg.Player.LIFE_INITIALIZED then
		on_player_life_initialized(self, message)
	elseif message_id == Msg.Player.LIFE_CHANGED then
		on_player_life_changed(self, message)
	elseif message_id == Msg.Player.SPECIAL_ACTION_USED then
		on_player_special_action_used(self, message)
	end
end
