local UtilsGUI = require("utils.utils_gui")
local Inputs = require("lib.inputs")
local Msg = require("lib.msg")

local ActionIds = {
	TouchMulti = hash("touch_multi"),
	Touch = hash("touch"),
}

local Urls = {
	GameController = "/controller",
	PlayerController = "/player/root#controller",
	MoveZone = "move_zone",
	MovePad = "move_pad",
	MoveController = "move_controller",
	Button = "button",
	Footer = "footer",
}

local ActionStatus = {
	Idle = hash("idle"),
	LongPressed = hash("long_pressed"),
	Pressed = hash("pressed"),
}

local function get_empty_button_action()
	local button_node = gui.get_node(Urls.Button)

	return {
		enabled = false,
		touch_id = nil,
		state = ActionStatus.Idle,
		position = vmath.vector3(0),
		original_position = gui.get_position(button_node),
		time = 0,
	}
end

function init(self)
	msg.post(".", "acquire_input_focus")

	local move_pad_node = gui.get_node(Urls.MovePad)
	local move_controller_node = gui.get_node(Urls.MoveController)
	local button_node = gui.get_node(Urls.Button)

	self.original_move_pad_position = gui.get_position(move_pad_node)
	self.original_move_controller_position = gui.get_position(move_controller_node)

	self.move_zone_action = {
		enabled = true,
		touch_id = nil,
		state = ActionStatus.Idle,
		position = vmath.vector3(0),
	}
	self.button_action = get_empty_button_action()
	self.controls_blocked = false
	self.debug = {
		enabled = true,
		keyboard_direction = vmath.vector3()
	}

	gui.set_enabled(button_node, false)
end

local BUTTON_ACTION_ENABLED_ALPHA = 1
local BUTTON_ACTION_DISABLED_ALPHA = 0.4
local function set_special_action_enabled(self, enabled)
	local button_node = gui.get_node(Urls.Button)

	self.button_action.enabled = enabled
	gui.set_enabled(button_node, true)
	gui.set(button_node, "color.w", enabled and BUTTON_ACTION_ENABLED_ALPHA or BUTTON_ACTION_DISABLED_ALPHA)
end

local function hide_button_action(self)
	local button_node = gui.get_node(Urls.Button)
	gui.set_position(button_node, self.button_action.original_position)


	self.button_action = get_empty_button_action()

	gui.set_enabled(button_node, false)
end

local function on_enable_move(self, message)
	self.controls_blocked = false
	self.move_zone_action.enabled = true
end

local function on_disable_move(self, message)
	self.move_zone_action.enabled = false
end

local function on_enable_special_action(self, message)
	message = message or {}
	set_special_action_enabled(self, true)
	self.button_action.movable = message.movable
end

local function on_disable_special_action(self, message)
	set_special_action_enabled(self, false)
end

local function on_hide_special_action(self, message)
	hide_button_action(self)
end

function on_message(self, message_id, message, sender)
	if message_id == Msg.ControlsUI.ENABLE_SPECIAL_ACTION then
		on_enable_special_action(self, message)
	elseif message_id == Msg.ControlsUI.DISABLE_SPECIAL_ACTION then
		on_disable_special_action(self, message)
	elseif message_id == Msg.ControlsUI.HIDE_SPECIAL_ACTION then
		on_hide_special_action(self, message)
	elseif message_id == Msg.ControlsUI.ENABLE_MOVE then
		on_enable_move(self, message)
	elseif message_id == Msg.ControlsUI.DISABLE_MOVE then
		on_disable_move(self, message)
	elseif message_id == Msg.ControlsUI.BLOCK_CONTROLS then
		self.controls_blocked = true
	end
end

local function update_button_time_pipe(self, dt)
	if self.button_action.state ~= ActionStatus.Idle then
		self.button_action.time = self.button_action.time + dt
	end
end

function update(self, dt)
	update_button_time_pipe(self, dt)
end

local MAX_MOVE_CONTROLLER_DISTANCE = 20

local function input_move_zone(self, touched)
	local touch_position = vmath.vector3(touched.x, touched.y, 1)
	local move_pad_node = gui.get_node(Urls.MovePad)
	local move_zone_node = gui.get_node(Urls.MoveZone)
	local move_controller_node = gui.get_node(Urls.MoveController)

	local container_position = gui.get_position(move_zone_node)

	if self.move_zone_action.state == ActionStatus.Idle and touched.pressed then
		self.move_zone_action.state = ActionStatus.Pressed
		self.move_zone_action.touch_id = touched.id
		self.move_zone_action.position = touch_position

		local position = touch_position - container_position

		gui.set_position(move_pad_node, position)
		gui.set_position(move_controller_node, position)
		return
	end

	if self.move_zone_action.state == ActionStatus.Pressed and touched.released then
		self.move_zone_action.state = ActionStatus.Idle
		self.move_zone_action.touch_id = nil
		self.move_zone_action.position = vmath.vector3(0)

		gui.set_position(move_pad_node, self.original_move_pad_position)
		gui.set_position(move_controller_node, self.original_move_controller_position)

		msg.post(Urls.PlayerController, Msg.Player.STOP_MOVE)
		return
	end

	if self.move_zone_action.state == ActionStatus.Pressed then
		local delta = touch_position - self.move_zone_action.position
		local distance = vmath.length(delta)
		local direction = distance > 0 and vmath.normalize(delta) or vmath.vector3(0)

		if distance > MAX_MOVE_CONTROLLER_DISTANCE then
			delta = direction * MAX_MOVE_CONTROLLER_DISTANCE
		end

		local move_pad_position = gui.get_position(move_pad_node)
		gui.set_position(move_controller_node, move_pad_position + delta)

		msg.post(Urls.PlayerController, Msg.Player.MOVE, {
			direction = direction,
			force = distance,
		})
	end
end

local MAX_BUTTON_ACTION_DISTANCE = 10
local LONG_PRESS_THRESHOLD = 0.35
local function input_button(self, touched)
	local button_node = gui.get_node(Urls.Button)

	local touch_position = vmath.vector3(touched.x, touched.y, 1)

	if touched.pressed and self.button_action.state == ActionStatus.Idle then
		self.button_action.state = ActionStatus.Pressed
		self.button_action.touch_id = touched.id
		self.button_action.position = touch_position
		self.button_action.time = 0

		msg.post(Urls.PlayerController, Msg.Player.START_SPECIAL_ACTION)
		msg.post(Urls.GameController, Msg.ControlsUI.SPECIAL_ACTION_PRESSED)
		return true
	end

	if self.button_action.state == ActionStatus.Pressed then
		if self.button_action.time > LONG_PRESS_THRESHOLD then
			self.button_action.state = ActionStatus.LongPressed
			msg.post(Urls.PlayerController, Msg.Player.RUN_SPECIAL_ACTION)
		end
	end

	if touched.released and self.button_action.state ~= ActionStatus.Idle then
		local previous_state = self.button_action.state

		self.button_action.state = ActionStatus.Idle
		self.button_action.touch_id = nil
		self.button_action.position = vmath.vector3(0)
		self.button_action.time = 0

		gui.set_position(button_node, self.button_action.original_position)

		local release_message = previous_state == ActionStatus.LongPressed and
				Msg.Player.RELEASE_SPECIAL_ACTION or Msg.Player.CANCEL_SPECIAL_ACTION
		msg.post(
			Urls.PlayerController,
			release_message
		)
		msg.post(Urls.GameController, Msg.ControlsUI.SPECIAL_ACTION_RELEASED)
		return true
	end

	if self.button_action.state == ActionStatus.LongPressed then
		local delta = touch_position - self.button_action.position
		local distance = vmath.length(delta)
		local direction = distance > 0 and vmath.normalize(delta) or vmath.vector3(0)

		if distance > MAX_BUTTON_ACTION_DISTANCE then
			delta = direction * MAX_BUTTON_ACTION_DISTANCE
			distance = MAX_BUTTON_ACTION_DISTANCE
		end

		gui.set_position(button_node, self.button_action.original_position + delta)

		msg.post(Urls.PlayerController, Msg.Player.MOVE_SPECIAL_ACTION, {
			direction = direction,
			force = distance / MAX_BUTTON_ACTION_DISTANCE,
		})

		return true
	end

	return false
end

local function input_keyboards(self, action_id, action)
	if not action_id then
		return false
	end

	local is_up = action_id == Inputs.Up
	local is_down = action_id == Inputs.Down
	local is_left = action_id == Inputs.Left
	local is_right = action_id == Inputs.Right

	if not (is_up or is_down or is_left or is_right) then
		return false
	end

	local x_direction = is_left and -1 or is_right and 1 or 0
	local y_direction = is_up and 1 or is_down and -1 or 0

	if action.pressed then
		self.debug.keyboard_direction = self.debug.keyboard_direction + vmath.vector3(x_direction, y_direction, 0)
	elseif action.released then
		self.debug.keyboard_direction = self.debug.keyboard_direction - vmath.vector3(x_direction, y_direction, 0)
	end

	if vmath.length(self.debug.keyboard_direction) == 0 then
		msg.post(Urls.PlayerController, Msg.Player.STOP_MOVE)
		return true
	end

	msg.post(Urls.PlayerController, Msg.Player.MOVE, {
		direction = vmath.normalize(self.debug.keyboard_direction),
		force = 1,
	})

	return true
end

local function input_action(self, action_id, action)
	return false
end

function on_input(self, action_id, action)
	if self.controls_blocked then
		return false
	end

	local handled = false
	if action_id == ActionIds.TouchMulti or action_id == ActionIds.Touch then
		local move_zone_node = gui.get_node(Urls.MoveZone)
		local button_node = gui.get_node(Urls.Button)

		if self.move_zone_action.enabled then
			local touched = UtilsGUI.get_touched_by_node(move_zone_node, action)
			if touched then
				input_move_zone(self, touched)
				handled = true
			end
		end

		if self.button_action.enabled then
			local touched = UtilsGUI.get_touched_by_node(button_node, action)
			if touched then
				input_button(self, touched)
				handled = true
			end
		end
	end

	if self.debug.enabled then
		if input_keyboards(self, action_id, action) then
			handled = true
		end

		if input_action(self, action_id, action) then
			handled = true
		end
	end

	return handled
end
