local BufferMakerBox = require("utils.buffer_maker.box")

go.property("width", 100)
go.property("height", 100)
go.property("color", vmath.vector4(1, 1, 1, 1))

local Urls = {
	Mesh = "#mesh"
}

function init(self)
	self.time = 0
	self.box = BufferMakerBox.new({
		mesh_url = Urls.Mesh,
		width = self.width,
		height = self.height,
		color = self.color,
	})
end

function final(self)
	self.box:final()
end

function update(self, dt)
	self.time = self.time + dt
	go.set(Urls.Mesh, "u_time.x", self.time)
end
