local Msg = require("lib.msg")

local GameState = {
	None = 0,
	Loading = 1,
	InGame = 2,
	GameOver = 3,
}

local Urls = {
	GameProxy = "/proxies#game_proxy",
	GameOverProxy = "/proxies#game_over_proxy",
}

function init(self)
	self.state = GameState.None
	msg.post(Urls.GameProxy, "load")
end

function final(self)
end

function update(self, dt)
end

function fixed_update(self, dt)
end

local function on_game_over(self, message)
	msg.post(Urls.GameProxy, "disable")
	msg.post(Urls.GameProxy, "final")
	msg.post(Urls.GameProxy, "unload")

	msg.post(Urls.GameOverProxy, "load")
end

local PROXY_FRAGMENT_MAP = {
	-- TODO: [hash("home")] = Urls.HomeProxy,
	[hash("game_over")] = Urls.GameOverProxy,
}
local function on_new_game(self, message, sender_socket)
	local proxy = PROXY_FRAGMENT_MAP[sender_socket]

	msg.post(proxy, "disable")
	msg.post(proxy, "final")
	msg.post(proxy, "unload")

	msg.post(Urls.GameProxy, "load")
end

function on_message(self, message_id, message, sender)
	if message_id == Msg.PROXY_LOADED then
		pprint("PROXY_LOADED", sender, message)
		if sender == msg.url(Urls.GameProxy) then
			msg.post(sender, "enable")
			msg.post(sender, "acquire_input_focus")
			-- msg.post(sender, "set_time_step", { factor = 0.25, mode = 0 })
			--msg.post(Urls.GameOver, "acquire_input_focus")

			self.state = GameState.InGame
		end

		if sender == msg.url(Urls.GameOverProxy) then
			self.state = GameState.GameOver
			msg.post(sender, "enable")
			msg.post(sender, "acquire_input_focus")
		end
	elseif message_id == Msg.Main.GAME_OVER then
		on_game_over(self, message)
	elseif message_id == Msg.Main.NEW_GAME then
		on_new_game(self, message, sender.socket)
	end
end

function on_input(self, action_id, action)
end

function on_reload(self)
end
