local GameState = {
	None = 0,
	Loading = 1,
	InGame = 2,
	GameOver = 3,
}

local Urls = {
	GameProxy = "/proxies#game_proxy",
	GameOverProxy = "/proxies#game_over_proxy",
}

function init(self)
	self.state = GameState.None
	msg.post(Urls.GameProxy, "load")
end

function final(self)
end

function update(self, dt)
end

function fixed_update(self, dt)
end

local MSG_PROXY_UNLOADED = hash("proxy_unloaded")
local MSG_PROXY_LOADED = hash("proxy_loaded")
local MSG_GAME_OVER = hash("game_over")

local function on_game_over(self, message)
	msg.post(Urls.GameProxy, "disable")
	msg.post(Urls.GameProxy, "final")
	msg.post(Urls.GameProxy, "unload")

	msg.post(Urls.GameOverProxy, "load")
end

function on_message(self, message_id, message, sender)
	if message_id == MSG_PROXY_LOADED then
		if sender == msg.url(Urls.GameProxy) then
			msg.post(sender, "enable")
			msg.post(sender, "acquire_input_focus")
			-- msg.post(sender, "set_time_step", { factor = 0.25, mode = 0 })

			--msg.post(Urls.GameOver, "acquire_input_focus")

			self.state = GameState.InGame
		end

		if sender == msg.url(Urls.GameOverProxy) then
			self.state = GameState.GameOver
			msg.post(sender, "enable")
			msg.post(sender, "acquire_input_focus")
		end
	end

	if message_id == MSG_GAME_OVER then
		pprint("MSG_GAME_OVER")
		on_game_over(self, message)
	end

	if message_id == MSG_PROXY_UNLOADED then
	end
end

function on_input(self, action_id, action)
end

function on_reload(self)
end
