local PlayerStater = require("lib.stater.player_stater")
local Msg = require("lib.msg")

local StatesEnum = PlayerStater.StatesEnum

local Urls = {
	Camera = "/camera",
	Weapon = "weapon#controller",
	SessionManager = "/session_manager",
	SoundController = "/sound_controller",
}
local TriggerStatusEnum = {
	Pressed = hash("pressed"),
	Released = hash("released"),
}

go.property("velocity", 60)
go.property("lives", 3)
go.property("bullet_damage", 20)

function init(self)
	self.stater = PlayerStater:new({
		stats = {
			velocity = self.velocity,
			lives = self.lives,
		}
	})

	self.target_enemies = {}

	msg.post(Urls.SessionManager, Msg.Game.PLAYER_SET_LIFE_COUNT, {
		lives = self.lives,
	})
end

local function get_target_enemy(self)
	local player_position = go.get_position()

	for i = 1, 3 do
		local enemy = self.target_enemies[i]
		if enemy then
			local result = physics.raycast(player_position, enemy.position, { hash("wall"), hash("obstacle") })
			if not result then
				return enemy
			end
		end
	end

	return nil
end

local function target_enemies_pipe(self, dt)
	local enemy = get_target_enemy(self)

	if not enemy then
		local trigger_status = go.get(Urls.Weapon, "trigger_status")
		if trigger_status == TriggerStatusEnum.Pressed then
			msg.post(Urls.Weapon, Msg.Weapon.STOP_FIRING)
		end

		return
	end

	msg.post(Urls.Weapon, Msg.Weapon.FIRE, {
		direction = enemy.direction,
		damage = self.bullet_damage,
	})
end

function fixed_update(self, dt)
	self.stater:update(dt)
	target_enemies_pipe(self, dt)
end

local function on_move_pressed(self, message)
	local direction = message.direction
	self.stater:set_direction(direction)

	if self.stater.movement_active then
		return
	end

	self.stater.movement_active = true
	self.stater:apply_transition(StatesEnum.Move, {
		direction = direction,
	})
	msg.post(Urls.SoundController, Msg.Sound.PLAY_SFX_SOUND, { id = hash("steps"), random_pitch = true })
end

local function on_move_released(self, message)
	if self.stater.movement_active then
		self.stater:apply_transition(StatesEnum.Idle, {})
	end

	self.stater.movement_active = false
	msg.post(Urls.SoundController, Msg.Sound.STOP_SFX_SOUND, { id = hash("steps") })
end

local function on_apply_damage(self, message)
	self.stater:apply_transition(StatesEnum.Hurt, {
		damage = message.damage,
		direction = message.direction,
		force = message.force,
	})
	local stats = self.stater.stats
	stats.lives = stats.lives - 1

	msg.post(Urls.Camera, Msg.Camera.SHAKE, {
		shake_duration = 0.2,
		shake_magnitude = 2,
	})
	msg.post(Urls.SessionManager, Msg.Game.PLAYER_LIFE_CHANGED, {
		current_lives = self.stater.stats.lives,
		total_lives = self.lives,
	})
end

local function on_target_enemies(self, message)
	self.target_enemies = message.enemies
end

local function on_set_position(self, message)
	go.set_position(message.position)
end

function on_message(self, message_id, message, sender)
	if message_id == Msg.Player.MOVE_PRESSED then
		on_move_pressed(self, message)
	elseif message_id == Msg.Player.MOVE_RELEASED then
		on_move_released(self, message)
	elseif message_id == Msg.APPLY_DAMAGE then
		on_apply_damage(self, message)
	elseif message_id == Msg.Player.SET_TARGET_ENEMIES then
		on_target_enemies(self, message)
	elseif message_id == Msg.Player.SET_POSITION then
		on_set_position(self, message)
	end
end

function on_reload(self)
end
