local PlayerStater = require("lib.stater.player_stater")
local Msg = require("lib.msg")

local StatesEnum = PlayerStater.StatesEnum

local Urls = {
	Camera = "/camera",
	Weapon = "weapon#controller",
	GameController = "/controller",
	SoundController = "/sound_controller",
	SuperActionsFactories = "super_actions_factories",
}

local TriggerStatusEnum = {
	Pressed = hash("pressed"),
	Released = hash("released"),
}

go.property("velocity", 60)
go.property("lives", 3)
go.property("bullet_damage", 20)
go.property("default_super_action", hash("none"))

local MAP_SUPER_ACTIONS = {
	[hash("vortex_zone")] = "#vortex_zone_factory",
	[hash("repulse_box")] = "#repulse_box_factory"
}
local function set_default_super_action(self)
	if self.default_super_action == hash("none") then return end

	local super_action_factory = MAP_SUPER_ACTIONS[self.default_super_action]
	if not super_action_factory then return end

	self.super_action_id = factory.create(Urls.SuperActionsFactories .. super_action_factory)
end

function init(self)
	self.stater = PlayerStater:new({
		stats = {
			velocity = self.velocity,
			lives = self.lives,
		}
	})

	self.target_enemies = {}

	msg.post(Urls.GameController, Msg.Game.PLAYER_SET_LIFE_COUNT, {
		lives = self.lives,
	})

	set_default_super_action(self)
end

local function get_target_enemy(self)
	local player_position = go.get_position()

	for i = 1, 3 do
		local enemy = self.target_enemies[i]
		if enemy then
			local result = physics.raycast(player_position, enemy.position, { hash("wall"), hash("obstacle") })
			if not result then
				return enemy
			end
		end
	end

	return nil
end

local function target_enemies_pipe(self, dt)
	local enemy = get_target_enemy(self)

	if not enemy then
		local trigger_status = go.get(Urls.Weapon, "trigger_status")
		if trigger_status == TriggerStatusEnum.Pressed then
			msg.post(Urls.Weapon, Msg.Weapon.RELEASE_WEAPON)
		end

		return
	end

	msg.post(Urls.Weapon, Msg.Weapon.TRIGGER_WEAPON, {
		direction = enemy.direction,
		damage = self.bullet_damage,
	})
end

function fixed_update(self, dt)
	self.stater:update(dt)
	target_enemies_pipe(self, dt)
end

local function on_move_pressed(self, message)
	local direction = message.direction
	self.stater:set_direction(direction)

	if self.stater.movement_active then
		return
	end

	self.stater.movement_active = true
	self.stater:apply_transition(StatesEnum.Move, {
		direction = direction,
	})
	msg.post(Urls.SoundController, Msg.Sound.PLAY_SFX_SOUND, { id = hash("steps"), random_pitch = true })
end

local function on_move_released(self, message)
	if self.stater.movement_active then
		self.stater:apply_transition(StatesEnum.Idle, {})
	end

	self.stater.movement_active = false
	msg.post(Urls.SoundController, Msg.Sound.STOP_SFX_SOUND, { id = hash("steps") })
end

local function on_apply_damage(self, message)
	self.stater:apply_transition(StatesEnum.Hurt, {
		damage = message.damage,
		direction = message.direction,
		force = message.force,
	})
	local stats = self.stater.stats
	stats.lives = stats.lives - 1

	msg.post(Urls.Camera, Msg.Camera.SHAKE, {
		shake_duration = 0.2,
		shake_magnitude = 2,
	})
	msg.post(Urls.GameController, Msg.Game.PLAYER_LIFE_CHANGED, {
		current_lives = self.stater.stats.lives,
		total_lives = self.lives,
	})
end

local function on_target_enemies(self, message)
	self.target_enemies = message.enemies
end

local function on_set_super_action(self, message)
	local super_factory = "#" .. message.id .. "_factory"
	self.super_action_id = factory.create(Urls.SuperActionsFactories .. super_factory)
end

local function on_pressed_super_action(self, message)
	if not self.super_action_id then return end
	-- msg.post(self.super_action_id, Msg.SuperAction.AIMING, {
	-- 	base_position = go.get_position(),
	-- 	direction = self.stater.direction,
	-- 	force = 0.5
	-- })
end

local function on_moved_super_action(self, message)
	if not self.super_action_id then return end

	msg.post(self.super_action_id, Msg.SuperAction.AIMING, {
		base_position = go.get_position(),
		direction = message.direction,
		force = message.force,
	})
end

local function on_released_super_action(self, message)
	if not self.super_action_id then return end
	msg.post(self.super_action_id, Msg.SuperAction.AIM_RELEASED)
end

function on_message(self, message_id, message, sender)
	if message_id == Msg.Player.MOVE_PRESSED then
		on_move_pressed(self, message)
	elseif message_id == Msg.Player.MOVE_RELEASED then
		on_move_released(self, message)
	elseif message_id == Msg.APPLY_DAMAGE then
		on_apply_damage(self, message)
	elseif message_id == Msg.Player.TARGET_ENEMIES then
		on_target_enemies(self, message)
	elseif message_id == Msg.Player.SET_SUPER_ACTION then
		on_set_super_action(self, message)
	elseif message_id == Msg.Player.PRESSED_SUPER_ACTION then
		on_pressed_super_action(self, message)
	elseif message_id == Msg.Player.RELEASED_SUPER_ACTION then
		on_released_super_action(self, message)
	elseif message_id == Msg.Player.MOVED_SUPER_ACTION then
		on_moved_super_action(self, message)
	end
end

function on_reload(self)
end
