local LimitStateTimer = require("lib.stater.limit_state_timer")
local UtilsGUI = require("utils.utils_gui")
local Msg = require("lib.msg")

local ActionIds = {
	TouchMulti = hash("touch_multi"),
	Touch = hash("touch"),
}

local Urls = {
	GameController = "/controller",
	PlayerController = "/player/root#controller",
	MoveZone = "move_zone",
	MovePad = "move_pad",
	MoveController = "move_controller",
	Button = "button",
	LifeNode = "life_node",
	Footer = "footer",
	Wipe = "wipe",
	ShopModal = "shop_modal"
}

local ActionStates = {
	Idle = hash("idle"),
	Pressed = hash("pressed"),
}

function init(self)
	msg.post(".", "acquire_input_focus")


	local move_pad_node = gui.get_node(Urls.MovePad)
	local move_controller_node = gui.get_node(Urls.MoveController)
	local button_node = gui.get_node(Urls.Button)

	self.original_move_pad_position = gui.get_position(move_pad_node)
	self.original_move_controller_position = gui.get_position(move_controller_node)

	self.move_zone_action = {
		enabled = true,
		touch_id = nil,
		state = ActionStates.Idle,
		position = vmath.vector3(0),
	}
	self.button_action = {
		enabled = true,
		touch_id = nil,
		state = ActionStates.Idle,
		position = vmath.vector3(0),
		original_position = gui.get_position(button_node),
	}

	self.direction_keyboard = vmath.vector3(0)

	self.life_nodes = {}
end

function final(self)
	-- Add finalization code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

local function wipe_view_pipe(self, dt)
	if not self.wipe_timer then return end

	self.wipe_timer:update(dt)
	if self.wipe_timer:is_expired() then
		self.wipe_timer = nil
		return
	end

	local progress = self.wipe_timer:progress()

	local wipe_node = gui.get_node(Urls.Wipe)

	gui.set(wipe_node, "progress.x", progress + 0.1)
end

function update(self, dt)
	wipe_view_pipe(self, dt)
end

local LIFE_NODE_SPACING = 32
local function on_set_life_count(self, message)
	local original_life_node = gui.get_node(Urls.LifeNode)
	local original_life_node_position = gui.get_position(original_life_node)
	local life_count = message.lives

	for i = 1, life_count do
		local life_node_id = "life_node_" .. i
		local life_node = gui.clone(original_life_node)
		local life_node_position = original_life_node_position + vmath.vector3((i - 1) * LIFE_NODE_SPACING, 0, 0)
		gui.set_position(life_node, life_node_position)
		gui.set_visible(life_node, true)
		gui.set_id(life_node, life_node_id)

		table.insert(self.life_nodes, { id = life_node_id, active = true })
	end
end

local function shake_life_node(self, life_node)
	local life_node_position = gui.get_position(life_node)
	gui.animate(life_node, "position.x", life_node_position.x + 2, gui.EASING_INBOUNCE, 0.125, 0, function()
		gui.animate(life_node, "position.x", life_node_position.x, gui.EASING_OUTBOUNCE, 0.125, 0)
	end)
end

local function on_player_life_changed(self, message)
	local current_lives = message.current_lives + 1

	for index, life in ipairs(self.life_nodes) do
		local life_node = gui.get_node(life.id)

		if index < current_lives then
			life.active = true
			gui.play_flipbook(life_node, "life")
		else
			-- was active
			if life.active then
				shake_life_node(self, life_node)
			end
			life.active = false
			gui.play_flipbook(life_node, "life_empty")
		end
	end
end

local function on_show_wipe(self, message)
	local wipe_node = gui.get_node(Urls.Wipe)
	gui.set_visible(wipe_node, true)
	self.wipe_timer = LimitStateTimer:new({
		duration = message.duration or 0.5,
	})
end

local function on_toggle_move(self, enabled)
	self.move_zone_action.enabled = enabled
end

local function on_toggle_button_action(self, enabled)
	self.button_action.enabled = enabled
end

local function on_show_shop_modal(self, message)
	local shop_modal_node = gui.get_node(Urls.ShopModal)
	gui.set_enabled(shop_modal_node, true)
end

function on_message(self, message_id, message, sender)
	if message_id == Msg.UI.SET_LIFE_NODES then
		on_set_life_count(self, message)
	elseif message_id == Msg.UI.LIFE_CHANGED then
		on_player_life_changed(self, message)
	elseif message_id == Msg.UI.SHOW_WIPE then
		on_show_wipe(self, message)
	elseif message_id == Msg.UI.ENABLE_BUTTON_ACTION then
		on_toggle_button_action(self, true)
	elseif message_id == Msg.UI.DISABLE_BUTTON_ACTION then
		on_toggle_button_action(self, false)
	elseif message_id == Msg.UI.ENABLE_MOVE then
		on_toggle_move(self, true)
	elseif message_id == Msg.UI.DISABLE_MOVE then
		on_toggle_move(self, false)
	elseif message_id == Msg.UI.SHOW_SHOP_MODAL then
		on_show_shop_modal(self, message)
	end
end

local MAX_MOVE_CONTROLLER_DISTANCE = 20

local function input_move_zone(self, touched)
	local touch_position = vmath.vector3(touched.x, touched.y, 1)
	local move_pad_node = gui.get_node(Urls.MovePad)
	local move_controller_node = gui.get_node(Urls.MoveController)
	local footer_node = gui.get_node(Urls.Footer)

	if self.move_zone_action.state == ActionStates.Idle and touched.pressed then
		self.move_zone_action.state = ActionStates.Pressed
		self.move_zone_action.touch_id = touched.id
		self.move_zone_action.position = touch_position

		local position = touch_position - gui.get_position(footer_node)

		gui.set_position(move_pad_node, position)
		gui.set_position(move_controller_node, position)
		return
	end

	if self.move_zone_action.state == ActionStates.Pressed and touched.released then
		self.move_zone_action.state = ActionStates.Idle
		self.move_zone_action.touch_id = nil
		self.move_zone_action.position = vmath.vector3(0)

		gui.set_position(move_pad_node, self.original_move_pad_position)
		gui.set_position(move_controller_node, self.original_move_controller_position)

		msg.post(Urls.PlayerController, Msg.Player.MOVE_RELEASED)
		return
	end

	if self.move_zone_action.state == ActionStates.Pressed then
		local delta = touch_position - self.move_zone_action.position
		local distance = vmath.length(delta)
		local direction = distance > 0 and vmath.normalize(delta) or vmath.vector3(0)

		if distance > MAX_MOVE_CONTROLLER_DISTANCE then
			delta = direction * MAX_MOVE_CONTROLLER_DISTANCE
		end

		local move_pad_position = gui.get_position(move_pad_node)
		gui.set_position(move_controller_node, move_pad_position + delta)

		msg.post(Urls.PlayerController, Msg.Player.MOVE_PRESSED, {
			direction = direction,
			force = distance,
		})
	end
end

local function input_button(self, touched)
end

function on_input(self, action_id, action)
	local handled = false
	if action_id == ActionIds.TouchMulti or action_id == ActionIds.Touch then
		local move_zone_node = gui.get_node(Urls.MoveZone)
		local button_node = gui.get_node(Urls.Button)

		if self.move_zone_action.enabled then
			local touched = UtilsGUI.get_touched_by_node(move_zone_node, action)
			if touched then
				input_move_zone(self, touched)
				handled = true
			end
		end

		if self.button_action.enabled then
			local touched = UtilsGUI.get_touched_by_node(button_node, action)
			if touched then
				input_button(self, touched)
				handled = true
			end
		end
	end

	return handled
end

function on_reload(self)
	-- Add reload-handling code here
	-- Learn more: https://defold.com/manuals/hot-reload/
	-- Remove this function if not needed
end
