local Msg = require("lib.msg")
local Entity = require("utils.entity")
local GameTime = require("modules.game_time")
local VMath = require("utils.vmath")
local Weapon = require("utils.weapon.weapon")
local ShotgunWeapon = require("utils.weapon.shotgun_weapon")
local WeaponConfigs = require("utils.weapon.configs")

local TriggerStatusEnum = {
  Pressed = hash("pressed"),
  Released = hash("released"),
}

local Urls = {
  BulletSmFactory = "#bullet_sm_factory",
  Sprite = "#sprite",
}

go.property("weapon_type", hash("Pistol"))
go.property("ammo_capacity", 0)
go.property("bullet_damage", 0)
go.property("bullet_force", 0)
go.property("bullet_speed", 0)
go.property("reload_time", 0)
go.property("offset", vmath.vector3(0, 8.0, 0))
go.property("trigger_status", hash("released"))

local SPRITE_MAP = {
  [WeaponConfigs.WeaponIds.Pistol] = {
    Idle = "weapon_01"
  },
  [WeaponConfigs.WeaponIds.Rifle] = {
    Idle = "weapon_02"
  },
  [WeaponConfigs.WeaponIds.Shotgun] = {
    Idle = "weapon_03"
  },
}

local WEAPON_MAP = {
  [WeaponConfigs.WeaponIds.Pistol] = Weapon,
  [WeaponConfigs.WeaponIds.Rifle] = Weapon,
  [WeaponConfigs.WeaponIds.Shotgun] = ShotgunWeapon,
}

local function get_mixed_weapon_properties(self)
  local weapon_config = WeaponConfigs.Configs[self.weapon_type]

  local bullet_config = weapon_config.bullet_config or {}
  return {
    ammo_capacity = self.ammo_capacity ~= 0 and self.ammo_capacity or weapon_config.ammo_capacity,
    reload_time = self.reload_time ~= 0 and self.reload_time or weapon_config.reload_time,
    bullet_damage = self.bullet_damage ~= 0 and self.bullet_damage or weapon_config.bullet_damage,
    bullet_config = {
      speed = self.bullet_speed ~= 0 and self.bullet_speed or bullet_config.speed,
      force = self.bullet_force ~= 0 and self.bullet_force or bullet_config.force,
    },
  }
end

function init(self)
  local weapon_config = WeaponConfigs.Configs[self.weapon_type]
  local WeaponModule = WEAPON_MAP[self.weapon_type] or Weapon

  self.weapon = WeaponModule:new({
    id = self.weapon_type,
    config = weapon_config,
    auto_reload = false,
    bullet = {
      config = weapon_config.bullet_config,
      factory_url = Urls.BulletSmFactory,
    },
    target = hash("player"),
    bullet_props = { theme = 2, },
  })

  local weapon_properties = get_mixed_weapon_properties(self)
  self.weapon:set_properties(weapon_properties)

  sprite.play_flipbook(Urls.Sprite, SPRITE_MAP[self.weapon_type].Idle)
  Entity.hide_sprite(Urls.Sprite)

  self.original_position = go.get_position()
  self.original_offset = vmath.length(self.original_position) or 1
  self.current_direction = vmath.vector3(0, -1, 0)

  self.trigger_payload = {}

  self.parent_id = go.get_parent() or "."
end

local HALF_PI = math.pi / 2
local function set_place_from_direction(self, direction)
  local weapon_position, weapon_rotation = Entity.get_object_facing({
    direction = direction,
    offset = self.original_offset,
    z = 3,
    facing_angle = HALF_PI,
  })
  go.set(".", "position", weapon_position + self.offset)
  go.set(".", "rotation", weapon_rotation)
  sprite.set_hflip(Urls.Sprite, direction.x > 0)
end

local function trigger_weapon_pipe(self, dt)
  if self.trigger_status ~= TriggerStatusEnum.Pressed then return end
  if self.weapon:is_reloading() then return end

  self.current_direction = self.trigger_payload.direction
  set_place_from_direction(self, self.trigger_payload.direction)

  self.weapon:fire(self.trigger_payload)
end

function fixed_update(self, dt)
  -- TODO: check how to disable when hidden
  dt = GameTime.scale(dt)
  self.weapon:update(dt)
  trigger_weapon_pipe(self, dt)
end

function final(self)
  self.weapon:final()
  self.weapon = nil
end

local function on_trigger_weapon(self, message)
  self.trigger_status = TriggerStatusEnum.Pressed
  self.trigger_payload = message or {}
  self.trigger_payload.direction = self.trigger_payload.direction or vmath.vector3(0, -1, 0)
  self.trigger_payload.damage = self.trigger_payload.damage or self.weapon.config.bullet_damage
  self.trigger_payload.position = VMath.z_one(go.get_world_position())
end

local function on_release_weapon(self, message)
  self.trigger_status = TriggerStatusEnum.Released
  self.trigger_payload = nil
end

local function on_set_properties(self, message)
  message = message or {}
  if message.bullet_damage then
    self.bullet_damage = message.bullet_damage
  end
  self.weapon:set_properties(message)
end

local function on_bullet_finished(self, message)
  self.weapon:on_bullet_finished(message.id)
end

local function on_reload_started(self, message)
  -- sprite.play_flipbook(Urls.Sprite, "reload")
  go.set(".", "euler.z", 0)
  go.animate(".", "euler.z", go.PLAYBACK_LOOP_FORWARD, 360, go.EASING_INQUAD, 0.3, 0)
end

local function on_reload_completed(self, message)
  go.cancel_animations(".", "euler.z")
  go.set(".", "euler.z", 0)
  -- sprite.play_flipbook(Urls.Sprite, "idle")
end

local function on_force_reload(self, message)
  self.weapon:start_reload(true)
end

local function on_show_element(self, message)
  Entity.show_sprite(Urls.Sprite)
end

local function on_hide_element(self, message)
  self.trigger_status = TriggerStatusEnum.Released
  Entity.hide_sprite(Urls.Sprite)
end

local function on_set_direction(self, message)
  if self.weapon:is_reloading() then return end
  set_place_from_direction(self, message.direction)
end

local function on_weapon_config_query(self, message, sender)
  msg.post(sender, Msg.Weapon.CONFIG_RECEIVED, {
    config = self.weapon.config,
    bullet_config = self.weapon.bullet_config,
    attack_duration = self.weapon:get_attack_duration(),
  })
end

function on_message(self, message_id, message, sender)
  if message_id == Msg.SHOW_ELEMENT then
    on_show_element(self, message)
  elseif message_id == Msg.HIDE_ELEMENT then
    on_hide_element(self, message)
  elseif message_id == Msg.Weapon.REQUEST_CONFIG then
    on_weapon_config_query(self, message, sender)
  elseif message_id == Msg.Weapon.SET_DIRECTION then
    on_set_direction(self, message)
  elseif message_id == Msg.Weapon.FIRE then
    on_trigger_weapon(self, message)
  elseif message_id == Msg.Weapon.STOP_FIRING then
    on_release_weapon(self, message)
  elseif message_id == Msg.Weapon.SET_PROPERTIES then
    on_set_properties(self, message)
  elseif message_id == Msg.Bullet.FINISHED then
    on_bullet_finished(self, message)
    -- Reload Start/Completed
  elseif message_id == Msg.Weapon.RELOAD_STARTED then
    on_reload_started(self, message)
  elseif message_id == Msg.Weapon.RELOAD_COMPLETED then
    on_reload_completed(self, message)
  end
end
