local Msg = require("lib.msg")
local EnemyStater = require("lib.stater.enemy_stater")
local Entity = require("utils.entity")
local GameTime = require("modules.game_time")
local Steer = require("modules.steer")
local DistanceAttackChecker = require("utils.attacker.checkers.distance_attack")
local BasicAttack = require("utils.attacker.basic_attack")

local StatesEnum = EnemyStater.StatesEnum

local Urls = {
	LevelManager = "/level_manager",
	GameController = "/controller#controller",
	PlayerRoot = "/player/root",
	PlayerController = "/player/root#controller",
	--Inner
	Attack = "attack",
	AttackController = "attack#controller",
	ShadowSprite = "shadow#sprite",
}

go.property("health", 5)
go.property("wave_id", 0)
go.property("velocity", 40)

function init(self)
	self.store = {
		health = self.health,
		velocity = self.velocity,
		target = Urls.PlayerRoot,
	}
	self.stater = EnemyStater:new({
		store = self.store
	})

	self.steer = Steer:new({})
	self.attacker = BasicAttack:new({
		time_config = {
			prepare = 0.5,
			attack = 0.3,
			cooldown = 0.5,
		},
		checker = DistanceAttackChecker:new({
			target = Urls.PlayerRoot,
			max_distance = 30,
		}),
		attack_url = Urls.Attack,
	})

	self.stater:add_behaviors({
		{
			state = StatesEnum.Attack,
			condition = function()
				return self.attacker:can_execute()
			end,
			get_payload = function()
				return {
					attacker = self.attacker,
					target = self.store.target,
				}
			end,
		}
	})

	Entity.hide_entity()
	GameTime.register_id()
end

function final(self)
	GameTime.unregister_id()
end

function fixed_update(self, dt)
	dt = GameTime.scale(dt)
	self.stater:update(dt)
	if self.stater:is(StatesEnum.Despawn) then return end

	self.attacker:update(dt)

	local direction = self.steer:update(dt, {
		position = go.get_position(),
		target_position = go.get_position(Urls.PlayerController),
		-- debug = true,
	})

	if self.stater:is(StatesEnum.Attack) then return end

	self.stater:set_direction(direction)
	self.attacker:set_direction(direction)
end

local function on_apply_damage(self, message)
	if self.stater:is(StatesEnum.Hurt) then return end

	local direction, damage, force = message.direction, message.damage, message.force
	self.store.health = math.max(0, self.store.health - damage)
	self.stater:apply_transition(StatesEnum.Hurt, {
		damage = damage,
		direction = vmath.vector3(direction.x, direction.y, 0),
		force = force,
	})
end

local function reset_store(self)
	self.store.health = self.health
	self.store.velocity = self.velocity
end

local function on_activate_enemy(self, message)
	reset_store(self)
	sprite.play_flipbook(Urls.ShadowSprite, "default")
	self.stater:set_behavior_flag(true)
	self.stater:apply_transition(StatesEnum.Spawn, {})
	self.wave_id = message.wave_id
end

local function on_dead(self, message)
	msg.post(Urls.LevelManager, Msg.Enemy.ENEMY_KILLED, {
		enemy_id = go.get_id(),
		position = go.get_position(),
		wave_id = self.wave_id
	})
	self.stater:set_behavior_flag(false)
end

local function on_despawned(self, message)
	sprite.play_flipbook(Urls.ShadowSprite, "default")
	Entity.hide_entity()
	print("Enemy despawned => " .. go.get_id())
	msg.post(Urls.LevelManager, Msg.Enemy.CONFIRM_ENEMY_DESPAWN, {
		enemy_id = go.get_id(),
	})
end

local function on_game_time_changed(self, message)
	GameTime.on_change(message, self.stater.urls.VisualSprite, self.stater.urls.Body)
end

local function on_select_element(self, message)
	sprite.play_flipbook(Urls.ShadowSprite, "selected")
end

local function on_unselect_element(self, message)
	sprite.play_flipbook(Urls.ShadowSprite, "default")
end

function on_message(self, message_id, message, sender)
	if message_id == Msg.APPLY_DAMAGE then
		on_apply_damage(self, message)
	elseif message_id == Msg.Enemy.ACTIVATE_ENEMY then
		on_activate_enemy(self, message)
	elseif message_id == Msg.Game.GAME_TIME_CHANGED then
		on_game_time_changed(self, message)
	elseif message_id == Msg.Enemy.SELECT then
		on_select_element(self, message)
	elseif message_id == Msg.Enemy.UNSELECT then
		on_unselect_element(self, message)
	elseif message_id == Msg.STATE_CHANGED and message.next_state == StatesEnum.Dead then
		on_dead(self, message)
	elseif message_id == Msg.STATE_CHANGED and message.next_state == StatesEnum.Despawn then
		on_despawned(self, message)
	end
end
