local RewardsIndex = require("lib.rewards.index")
local Rewards = require("lib.rewards.reward_types")
local Table = require("utils.table")
local Msg = require("lib.msg")
local Entity = require("utils.entity")
local GameTime = require("modules.game_time")

local Urls = {
	-- External
	GameController = "/controller",
	StarFlareSprite = "#star_flare_sprite",
	SpecialUpgradeFactory = "#special_action_factory",
	StatusSelectorFactory = "#status_selector_factory",
	EnhancementUpgradeFactory = "#enhancement_upgrade_factory",
	SpecificStatusFactory = "#specific_status_factory",
}

local SpriteFactories = {
	[Rewards.SpecialAction] = Urls.SpecialUpgradeFactory,
	[Rewards.StatusSelector] = Urls.StatusSelectorFactory,
	[Rewards.EnhancementUpgrade] = Urls.EnhancementUpgradeFactory,
	[Rewards.EnhancementUpgrade] = Urls.SpecificStatusFactory,
}

local StarFlare = {
	RadialParams = vmath.vector4(0.0, 0.5, 0.0, 1.0),
	RotationVelocity = 1.0,
}

go.property("reward", hash("none"))

function init(self)
	self.elapsed_time = 0
	go.set(Urls.StarFlareSprite, "sprite_size", go.get(Urls.StarFlareSprite, "size"))
	go.set(Urls.StarFlareSprite, "radial_params", StarFlare.RadialParams)
	go.set(Urls.StarFlareSprite, "rotation_params.y", 1.5)

	-- local sprite_factory = SpriteFactories[self.reward]
	-- local sprite_id = factory.create(sprite_factory, go.get_position() + vmath.vector3(0, 0, 1))
	-- go.set_parent(sprite_id, go.get_id(), false)

	self.options = {}
	-- generate the rewards
	local options_list = RewardsIndex[self.reward]
	if options_list then
		self.options = Table.pick_random(options_list, 3)
	end
end

function final(self)
	-- Add finalization code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function update(self, dt)
	dt = GameTime.scale(dt)
	self.elapsed_time = self.elapsed_time + dt
	go.set(Urls.StarFlareSprite, "rotation_params.x", self.elapsed_time)
end

local function on_trigger_response(self, message)
	if not message.enter then return end

	msg.post(Urls.GameController, Msg.Game.OPEN_UPGRADER, {
		options = self.options
	})
end

local function on_remove_element()
	Entity.disable_body()
	go.animate(".", "scale", go.PLAYBACK_ONCE_FORWARD, vmath.vector3(0), go.EASING_INBACK, 0.3, 0.1,
		function()
			go.delete(".", true)
		end
	)
end

function on_message(self, message_id, message, sender)
	if message_id == Msg.TRIGGER_OCCURRED then
		on_trigger_response(self, message)
	elseif message_id == Msg.REMOVE_ELEMENT then
		on_remove_element()
	end
end
