local Msg = require("lib.msg")

local Urls = {
	MainController = "main:/main_controller"
}

function init(self)
	self.start_pressed = false
	msg.post(".", "acquire_input_focus")
end

local function pressed_button(button, label)
	gui.play_flipbook(button, "pressed", nil)
	gui.animate(label, "position.y", -2, gui.EASING_LINEAR, 0.1, 0)
end

local function unpressed_button(button, label)
	gui.play_flipbook(button, "unpressed")
	gui.animate(label, "position.y", 1.5, gui.EASING_LINEAR, 0.1, 0)
end

local function input_start(self, action)
	local button = gui.get_node("start_button")
	local label = gui.get_node("start_label")

	if action.pressed and gui.pick_node(button, action.x, action.y) then
		pressed_button(button, label)
		self.start_pressed = true
		return true
	end

	if self.start_pressed and not action.released and not gui.pick_node(button, action.x, action.y) then
		unpressed_button(button, label)
		self.start_pressed = false
		return false
	end

	if action.released and self.start_pressed then
		unpressed_button(button, label)
		self.start_pressed = false
		msg.post(Urls.MainController, Msg.Main.START_NEW_GAME)
		return true
	end

	return false
end

function on_input(self, action_id, action)
	if action_id == hash("touch") then
		return input_start(self, action)
	end

	return false
end

function on_reload(self)
	msg.post(".", "acquire_input_focus")
end
