local Colors = require("lib.colors")
local Msg = require("lib.msg")
local Entity = require("utils.entity")
local VMath = require("utils.vmath")
local Weapon = require("utils.weapon.weapon")
local WeaponConfigs = require("utils.weapon.configs")

local TriggerStatusEnum = {
	Pressed = hash("pressed"),
	Released = hash("released"),
}

local Urls = {
	BulletSmFactory = "#bullet_sm_factory",
	Sprite = "#sprite",
	MuzzleFlash = "#muzzle_flash",
	SoundController = "/sound_controller",
}

go.property("ammo_capacity", 4)
go.property("bullet_damage", 2)
go.property("bullet_force", 3)
go.property("bullet_speed", 400)
go.property("offset", vmath.vector3(0, 8.0, 0))
go.property("trigger_status", hash("released"))

function init(self)
	self.weapon = Weapon:new({
		id = "pistol",
		config = WeaponConfigs.WeaponConfigs.Pistol,
		bullet = {
			config = WeaponConfigs.BulletConfigs.Pistol,
			factory_url = Urls.BulletSmFactory,
		},
		target = hash("enemy"),
		bullet_props = {
			theme = 1,
		},
	})

	self.weapon:set_properties({
		ammo_capacity = self.ammo_capacity,
		pool_size = self.ammo_capacity + 2,
		bullet_config = {
			speed = self.bullet_speed,
			force = self.bullet_force,
		},
	})

	self.original_position = go.get_position()
	self.original_offset = vmath.length(self.original_position) or 1
	self.current_direction = vmath.vector3(0, -1, 0)

	go.set(Urls.Sprite, "target_color_1", vmath.vector4(unpack(Colors["#ffffeb"])))
	go.set(Urls.Sprite, "target_color_2", vmath.vector4(unpack(Colors["#422445"])))
	go.set(Urls.Sprite, "target_color_3", vmath.vector4(unpack(Colors["#f2a65e"])))
	go.set(Urls.Sprite, "target_color_4", vmath.vector4(unpack(Colors["#ffe478"])))
	go.set(Urls.Sprite, "target_color_5", vmath.vector4(unpack(Colors["#e36956"])))
	self.trigger_payload = {}

	Entity.hide_sprite(Urls.MuzzleFlash)
	local color3 = vmath.vector4(unpack(Colors["#ffe478"])) * 0.5
	go.set(Urls.MuzzleFlash, "target_color_1", vmath.vector4(unpack(Colors["#ffffeb"])))
	go.set(Urls.MuzzleFlash, "target_color_2", vmath.vector4(unpack(Colors["#f2a65e"])))
	go.set(Urls.MuzzleFlash, "target_color_3", color3)
end

local HALF_PI = math.pi / 2
local POINTING_DIRECTION_THRESHOLD = 0.175

local function trigger_weapon_pipe(self, dt)
	if self.trigger_status ~= TriggerStatusEnum.Pressed then return end
	if self.weapon:is_reloading() then return end

	local current_direction = self.current_direction
	local target_direction = self.trigger_payload.direction
	local distance = vmath.length(current_direction - target_direction)

	if distance ~= 0 then
		self.current_direction = vmath.lerp(dt * 7, current_direction, target_direction)
		local weapon_position, weapon_rotation = Entity.get_object_facing({
			direction = self.current_direction,
			offset = self.original_offset,
			z = go.get(".", "position.z"),
			facing_angle = HALF_PI,
		})
		go.set(".", "position", weapon_position + self.offset)
		go.set(".", "rotation", weapon_rotation)

		if distance > POINTING_DIRECTION_THRESHOLD then
			return
		end
	end

	self.weapon:fire(self.trigger_payload)
end

function fixed_update(self, dt)
	self.weapon:update(dt)

	trigger_weapon_pipe(self, dt)
end

local function on_trigger_weapon(self, message)
	self.trigger_status = TriggerStatusEnum.Pressed
	self.trigger_payload = message or {}
	self.trigger_payload.direction = self.trigger_payload.direction or vmath.vector3(0, -1, 0)
	self.trigger_payload.position = VMath.z_one(go.get_world_position())
end

local function on_release_weapon(self, message)
	self.trigger_status = TriggerStatusEnum.Released
	self.trigger_payload = nil
end

local function on_bullet_finished(self, message)
	self.weapon:on_bullet_finished(message.id)
end

local function on_set_properties(self, message)
	self.weapon:set_properties(message)
end

local function on_reload_started(self, message)
	go.cancel_animations(Urls.MuzzleFlash, "tint.w")
	Entity.hide_sprite(Urls.MuzzleFlash)

	sprite.play_flipbook(Urls.Sprite, "reload")
	go.animate(".", "euler.z", go.PLAYBACK_LOOP_FORWARD, 360, go.EASING_INQUAD, 0.15, 0)
end

local function on_reload_completed(self, message)
	go.cancel_animations(".", "euler.z")
	go.set(".", "euler.z", 0)
	sprite.play_flipbook(Urls.Sprite, "idle")
end

local function show_muzzle_flash()
	go.cancel_animations(Urls.MuzzleFlash, "tint.w")
	Entity.show_sprite(Urls.MuzzleFlash)
	sprite.play_flipbook(Urls.MuzzleFlash, "muzzle_flash")
	go.animate(Urls.MuzzleFlash, "tint.w", go.PLAYBACK_ONCE_FORWARD, 0, go.EASING_OUTQUAD, 0.1, 0.1)
end

local function on_fire_weapon(self, message)
	sprite.play_flipbook(Urls.Sprite, "fire")
	show_muzzle_flash()
	msg.post(Urls.SoundController, Msg.Sound.PLAY_SFX_SOUND, { id = hash("shot") })
end

function on_message(self, message_id, message, sender)
	if message_id == Msg.Weapon.FIRE then
		on_trigger_weapon(self, message)
	elseif message_id == Msg.Weapon.STOP_FIRING then
		on_release_weapon(self, message)
	elseif message_id == Msg.Weapon.SET_PROPERTIES then
		on_set_properties(self, message)
	elseif message_id == Msg.Bullet.FINISHED then
		on_bullet_finished(self, message)
	elseif message_id == Msg.Weapon.FIRED then
		on_fire_weapon(self, message)
	elseif message_id == Msg.Weapon.RELOAD_STARTED then
		on_reload_started(self, message)
	elseif message_id == Msg.Weapon.RELOAD_COMPLETED then
		on_reload_completed(self, message)
	end
end
