local VMath = require("utils.vmath")
local Msg = require("lib.msg")
local Entity = require("utils.entity")

local Urls = {
	Body = "root#body",
	BodyTrigger = "root#body_trigger",
	Visual = "visual",
	Sprite = "visual#sprite",
	ShadowSprite = "shadow#sprite",
	-- External
	GameController = "/controller#controller",
}

local function clear_life_timer(self)
	if not self.current_life_timer then return end

	timer.cancel(self.current_life_timer)
	self.current_life_timer = nil
end

local function disabled_perrocoin(self)
	Entity.disable_body(Urls.Body)
	Entity.disable_body(Urls.BodyTrigger)
	Entity.hide_sprite(Urls.Sprite)
	Entity.hide_sprite(Urls.ShadowSprite)
	self.target = nil

	clear_life_timer(self)
end

local function enabled_perrocoin(self)
	Entity.enable_body(Urls.Body)
	Entity.enable_body(Urls.BodyTrigger)
	Entity.show_sprite(Urls.Sprite)
	Entity.show_sprite(Urls.ShadowSprite)

	self.current_chase_speed = self.chase_speed
	sprite.play_flipbook(Urls.Sprite, "perrocoin")
	self.current_life_timer = timer.delay(
		self.life_time,
		false,
		function()
			sprite.play_flipbook(Urls.Sprite, "perrocoin_disappear", function()
				msg.post(Urls.GameController, Msg.Game.PERROCOIN_EXPIRED, {
					perrocoin_id = go.get_id(),
				})
				disabled_perrocoin(self)
			end)
		end
	)
end

go.property("chase_speed", 100)
go.property("value", 1)
go.property("life_time", 3)

function init(self)
	disabled_perrocoin(self)
end

local DISTANCE_THRESHOLD = 5

local function chase_target_pipe(self, dt)
	if not self.target then return end

	local position = go.get_position()
	local target_position = go.get_position(self.target)
	local distance = vmath.length(position - target_position)

	if distance < DISTANCE_THRESHOLD then
		msg.post(Urls.GameController, Msg.Game.PERROCOIN_PICKED, {
			value = self.value,
			perrocoin_id = go.get_id(),
		})
		disabled_perrocoin(self)
		return
	end

	local direction = vmath.normalize(target_position - position)

	go.set(Urls.Body, "linear_velocity", direction * self.current_chase_speed)
end

function update(self, dt)
	chase_target_pipe(self, dt)
end

local function on_trigger_response(self, message)
	if not message.enter then return end

	self.target = msg.url(message.other_id)
end

local function on_show_element(self, message)
	enabled_perrocoin(self)

	self.value = message.value or self.value

	if message.position then
		go.set_position(message.position)
		local random_direction = VMath.random_direction()
		local target_position = message.position + random_direction * 10
		go.animate(".", "position", go.PLAYBACK_ONCE_FORWARD, target_position, go.EASING_OUTCUBIC, 0.3, 0.1, function()
			go.set(Urls.Visual, "position.y", 10.0)
			go.animate(
				Urls.Visual,
				"position.y",
				go.PLAYBACK_LOOP_PINGPONG,
				13.0,
				go.EASING_INOUTSINE,
				1.5,
				math.random() / 10.0
			)
		end)
	end
end

local function on_auto_collect_point(self, message)
	clear_life_timer(self)

	self.target = message.target

	local distance = vmath.length(go.get_position(self.target) - go.get_position())
	local time = message.time

	self.current_chase_speed = math.max(distance / time, self.chase_speed)
end

function on_message(self, message_id, message, sender)
	if message_id == Msg.HIDE_ELEMENT then
		disabled_perrocoin(self)
	elseif message_id == Msg.SHOW_ELEMENT then
		on_show_element(self, message)
	elseif message_id == Msg.TRIGGER_RESPONSE then
		on_trigger_response(self, message)
	elseif message_id == Msg.Game.AUTO_COLLECT_POINT then
		on_auto_collect_point(self, message)
	end
end
