local Stage = require("utils.stager.stage")
local WaveBuilder = require("utils.stager.wave_builder")
local EnemyPool = require("utils.pooler.enemy_pool")
local RandomPositionGenerator = require("utils.position_generator.random_position_generator")
local SetPositionGenerator = require("utils.position_generator.set_position_generator")
local TilesInfo = require("utils.tiles_info")
local VMath = require("utils.vmath")
local Msg = require("lib.msg")

local Urls = {
	FactoryEnemy01 = "/stage_manager#cfactory_enemy_01",
	FactoryEnemy02 = "/stage_manager#cfactory_enemy_02",
	Tilemap01Factory = "/stage_manager#tilemap_01_factory",
	Tilemap02Factory = "/stage_manager#tilemap_02_factory",
	PlayerController = "/player/root#controller",
	UpgraderFactory = "/stage_manager#upgrader_factory",
	DoorFactory = "/stage_manager#door_factory"
}

local FACTORIES_MAP = {
	enemy_01 = Urls.FactoryEnemy01,
	enemy_02 = Urls.FactoryEnemy02,
}

local TILEMAP_FACTORY_MAP = {
	[hash("tilemap_01")] = Urls.Tilemap01Factory,
	[hash("tilemap_02")] = Urls.Tilemap02Factory,
}

local DoorsEnum = {
	Normal = 10,
	Opened = 11,
	Random = 12,
	Hard = 13,
	Boss = 14,
}

local function spawn_doors(self, doors)
	local tiles_lg_url = msg.url(nil, self.current_tilemap.tiles_lg, "tileset")
	local bounds = TilesInfo.get_bounds(tiles_lg_url)

	local offset = go.get_position(self.current_tilemap.id)

	self.stage_info.doors = TilesInfo.get_doors_positions({
		offset = offset,
		bounds = bounds,
		doors_amount = #doors,
	})


	for index, door in ipairs(self.stage_info.doors) do
		tilemap.set_tile(tiles_lg_url, "walls", door.column_index, door.row_index, DoorsEnum.Normal)
		local door_id = factory.create(Urls.DoorFactory, door.position, nil, {
			door_option = doors[index],
		})
		door.id = door_id
	end
end

local function spawn_upgrader(self)
	if not self.stage_info.upgrader_position then return end

	self.upgrader_id = factory.create(Urls.UpgraderFactory, self.upgrader_position, nil, {
		reward = self.current_stage_reward
	})
end

local function on_stage_complete(self)
	spawn_upgrader(self)
end

local function parse_stage_info(self)
	local tiles_sm_url = msg.url(nil, self.current_tilemap.tiles_sm, "tileset")

	tilemap.set_visible(tiles_sm_url, "landmarks", false)

	return TilesInfo.get_landmark_info({
		offset = go.get_position(self.current_tilemap.id),
		landmarks_tiles = tilemap.get_tiles(tiles_sm_url, "landmarks"),
		bounds = TilesInfo.get_bounds(tiles_sm_url),
	})
end

go.property("debug", false)

function init(self)
	self.enemies_pool = EnemyPool.new({
		factory_map = FACTORIES_MAP,
		position_generator = RandomPositionGenerator:new(200, -200),
	})

	self.stage = Stage:new({
		max_overlap = 2,
		on_spawn = function(spawn_options)
			self.enemies_pool:acquire_or_extend({
				wave_id = spawn_options.wave_id,
				type = spawn_options.enemy.id,
			})
		end,
		on_wave_start = function(index, _wave)
			msg.post("#stage_manager", Msg.Wave.WAVE_STARTED, { index = index })
		end,
		on_stage_complete = function()
			on_stage_complete(self)
		end,
	})
end

local function target_enemies_pipe(self, dt)
	local active_enemies = self.enemies_pool:get_actives()
	local player_position = VMath.z_one(go.get_position(Urls.PlayerController))
	local enemy_positions = {}
	for _, enemy in ipairs(active_enemies) do
		local position = VMath.z_one(go.get_position(enemy.id)) + vmath.vector3(0, 12, 0)
		local delta = position - player_position
		table.insert(enemy_positions, {
			id = enemy.id,
			position = position,
			delta = delta,
			distance = vmath.length(delta),
			direction = vmath.normalize(delta)
		})
	end

	table.sort(enemy_positions, function(a, b)
		return a.distance < b.distance
	end)

	msg.post(Urls.PlayerController, Msg.Player.SET_TARGET_ENEMIES, {
		enemies = enemy_positions,
	})
end

function update(self, dt)
	self.stage:update(dt)
	target_enemies_pipe(self, dt)
end

local function on_enemy_killed(self, message)
	self.stage:on_enemy_killed(message.wave_id)
	self.enemies_pool:request_release(message.enemy_id)
end

local function on_confirm_enemy_despawn(self, message)
	self.enemies_pool:confirm_release(message.enemy_id)
end

local function on_load_stage(self, message)
	self.enemies_pool:reset()

	local stage_data = message.stage_node.data
	local next_doors = message.stage_node.doors
	self.current_stage_id = message.stage_id

	-- Create the tilemap
	local tilemap_factory = TILEMAP_FACTORY_MAP[stage_data.tilemap_id]
	if not tilemap_factory then
		error(("Stage factory not found for tilemap_id %s"):format(tostring(stage_data.tilemap_id)))
	end

	local ids = collectionfactory.create(tilemap_factory)
	self.current_tilemap = {
		id = ids["/root"],
		tiles_sm = ids["/tiles_sm"],
		tiles_lg = ids["/tiles_lg"],
	}

	self.stage_info = parse_stage_info(self)
	if next_doors then
		spawn_doors(self, next_doors)
	end

	self.enemies_pool:set_position_generator(SetPositionGenerator:new(self.stage_info.spawn_positions))

	self.current_stage_reward = stage_data.reward
	self.stage:set_waves(WaveBuilder.from_config(stage_data.waves))
	self.stage:start()
end

local function on_open_doors(self, _)
	go.animate(self.upgrader_id, "scale", go.PLAYBACK_ONCE_FORWARD, vmath.vector3(0), go.EASING_INBACK, 0.3, 0, function()
		go.delete(self.upgrader_id)
	end)

	local tiles_lg_url = msg.url(nil, self.current_tilemap.tiles_lg, "tileset")
	for _, door in ipairs(self.stage_info.doors) do
		msg.post(door.id, Msg.HIDE_ELEMENT)
		tilemap.set_tile(tiles_lg_url, "walls", door.column_index, door.row_index, DoorsEnum.Opened)
	end
end

function on_message(self, message_id, message, sender)
	if message_id == Msg.Stager.LOAD_STAGE then
		on_load_stage(self, message)
	elseif message_id == Msg.Enemy.ENEMY_KILLED then
		on_enemy_killed(self, message)
	elseif message_id == Msg.Stager.OPEN_DOORS then
		on_open_doors(self, message)
	elseif message_id == Msg.Enemy.CONFIRM_ENEMY_DESPAWN then
		on_confirm_enemy_despawn(self, message)
	end
end
