local Msg = require("lib.msg")
local TilesInfo = require("utils.tiles_info")
local Colors = require("lib.colors")

local Urls = {
	StageManger = "/stage_manger",
	PlayerController = "/player/root#controller",
	-- Inner
	UpgraderFactory = "root#upgrader_factory",
	DoorFactory = "root#door_factory",
	TilesLg = "tiles_lg#tileset",
	TilesSM = "tiles_sm#tileset",
}

go.property("stage_name", hash("stage_0"))
go.property("stage_width", 7)
go.property("stage_height", 11)


local DOOR_TILE_OPEN = 11

local function spawn_doors(doors_positions)
	local doors = {}
	for _, door_position in ipairs(doors_positions) do
		local door = factory.create(Urls.DoorFactory, door_position.position, nil, {})
		table.insert(doors, { id = door, column_index = door_position.column_index, row_index = door_position.row_index })
	end

	return doors
end

function init(self)
	tilemap.set_visible(Urls.TilesSM, "landmarks", false)

	local stage_info = TilesInfo.get_landmark_info({
		offset = go.get_position(),
		landmarks_tiles = tilemap.get_tiles(Urls.TilesSM, "landmarks"),
		bounds = TilesInfo.get_bounds(Urls.TilesSM)
	})

	self.upgrader_position = stage_info.upgrader_position
	self.doors = spawn_doors(stage_info.doors_positions)

	msg.post(
		Urls.StageManger,
		Msg.Wave.INIT_STAGE,
		{ spawn_positions = stage_info.spawn_positions }
	)
	msg.post("@render:", "clear_color", { color = vmath.vector4(unpack(Colors["#272736"])) })
end

function fixed_update(self, dt)
end

local function on_open_door(self, message)
	for _, door in ipairs(self.doors) do
		msg.post(door.id, Msg.HIDE_ELEMENT)
		local x = door.column_index
		local y = door.row_index
		tilemap.set_tile(Urls.TilesLg, "walls", x, y, DOOR_TILE_OPEN)
	end
end

local function on_stage_ended(self, message)
	on_open_door(self, message)
	factory.create(Urls.UpgraderFactory, self.upgrader_position, nil, {
		reward = message.reward
	})
end

function on_message(self, message_id, message, sender)
	if message_id == Msg.Stager.STAGE_ENDED then
		on_stage_ended(self, message)
	elseif message_id == Msg.Stager.OPEN_DOOR then
		on_open_door(self, message)
	end
end

function on_reload(self)
end
