local BufferBoxMaker = require("utils.buffer_maker.box")

go.property("width", 100)
go.property("height", 100)
go.property("color", vmath.vector4(1, 1, 1, 1))

local Urls = {
	Mesh = "#mesh"
}

function init(self)
	self.mesh_url = Urls.Mesh
	self.time = 0
	BufferBoxMaker.init(self)
end

function final(self)
	BufferBoxMaker.final(self)
end

function update(self, dt)
	self.time = self.time + dt;
	go.set(Urls.Mesh, "u_time.x", self.time)
end
