local Msg = require("lib.msg")
local EnemyStater = require("lib.stater.enemy_stater")
local Entity = require("utils.entity")
local Steer = require("modules.steer")
local WeaponAttack = require("utils.attacker.weapon_attack")

local StatesEnum = EnemyStater.StatesEnum

local Urls = {
	LevelManager = "/level_manager",
	GameController = "/controller#controller",
	PlayerRoot = "/player/root",
	PlayerController = "/player/root#controller",
	--Inner
	WeaponController = "weapon#controller"
}

go.property("health", 12)
go.property("wave_id", 0)
go.property("safe_distance", 100)
go.property("velocity", 30)
go.property("bullet_damage", 2)

function init(self)
	self.stater = EnemyStater:new({
		stats = {
			health = self.health,
			velocity = self.velocity,
		}
	})

	---@diagnostic disable-next-line: missing-fields
	self.steer = Steer:new({
		config = {
			safe_distance = self.safe_distance
		}
	})
	self.attacker = WeaponAttack:new({
		time_config = nil,
		attack_url = Urls.WeaponController,
	})

	self.stater:add_behaviors({
		{
			state = StatesEnum.Attack,
			condition = function()
				local player_position = go.get_position(Urls.PlayerController)
				local position = go.get_position()
				local distance = vmath.length(player_position - position)
				return self.steer:get_is_target_on_sight() and distance <= self.safe_distance and self.attacker:can_attack()
			end,
			get_payload = function()
				return {
					attacker = self.attacker,
					target = self.target,
				}
			end,
		}
	})

	Entity.hide_entity()

	msg.post(Urls.WeaponController, Msg.Weapon.REQUEST_CONFIG)
end

function fixed_update(self, dt)
	self.stater:update(dt)

	if self.stater:is(StatesEnum.Despawn) then return end

	self.attacker:update(dt)

	local position = go.get_position()
	local target_position = go.get_position(Urls.PlayerController)
	local weapon_direction = vmath.normalize(target_position - position)

	if not self.stater:is(StatesEnum.Attack) then
		self.attacker:set_direction(weapon_direction)
		msg.post(Urls.WeaponController, Msg.Weapon.SET_DIRECTION, {
			direction = weapon_direction,
		})
	end

	local direction = self.steer:update(dt, {
		position = position,
		target_position = target_position,
		enable_safe_distance = true,
		-- debug = true,
	})
	self.stater:set_direction(direction)
end

local function on_apply_damage(self, message)
	if self.stater:is(StatesEnum.Hurt) then return end

	-- if self.stater:is(StatesEnum.Attack) then
	-- 	local current_health = self.stater.stats.health
	-- 	self.stater.stats.health = current_health - message.damage
	-- 	return
	-- end

	local direction, damage, force = message.direction, message.damage, message.force
	self.stater:apply_transition(StatesEnum.Hurt, {
		damage = damage,
		direction = vmath.vector3(direction.x, direction.y, 0),
		force = force,
	})
end

local function on_activate_enemy(self, message)
	self.stater:apply_transition(StatesEnum.Spawn, {})
	msg.post(Urls.WeaponController, Msg.SHOW_ELEMENT)
	self.wave_id = message.wave_id
end

local function on_dead(self, message)
	msg.post(Urls.LevelManager, Msg.Enemy.ENEMY_KILLED, {
		enemy_id = go.get_id(),
		position = go.get_position(),
		wave_id = self.wave_id
	})
	msg.post(Urls.WeaponController, Msg.HIDE_ELEMENT)
end

local function on_despawned(self, message)
	Entity.hide_entity()
	print("Enemy despawned => " .. go.get_id())
	msg.post(Urls.LevelManager, Msg.Enemy.CONFIRM_ENEMY_DESPAWN, {
		enemy_id = go.get_id(),
	})
end

local function on_weapon_config_response(self, message)
	local config = message.config
	local cooldown = config.reload_time
	local attack = config.fire_interval * config.ammo_capacity

	self.attacker:set_time_config({
		prepare = 0.3,
		attack = attack,
		cooldown = cooldown,
	})
end

function on_message(self, message_id, message, sender)
	if message_id == Msg.APPLY_DAMAGE then
		on_apply_damage(self, message)
	elseif message_id == Msg.Enemy.ACTIVATE_ENEMY then
		on_activate_enemy(self, message)
	elseif message_id == Msg.Weapon.CONFIG_RECEIVED then
		on_weapon_config_response(self, message)
	elseif message_id == Msg.STATE_CHANGED and message.next_state == StatesEnum.Dead then
		on_dead(self, message)
	elseif message_id == Msg.STATE_CHANGED and message.next_state == StatesEnum.Despawn then
		on_despawned(self, message)
	end
end
