local Msg = require("lib.msg")
local Math = require("utils.math")
local Entity = require("utils.entity")

local Urls = {
	Bar = "#sprite_bar",
	Track = "track",
	TrackSprite = "track#sprite",
}

local function hide_element()
	Entity.hide_sprite(Urls.Bar)
	Entity.hide_sprite(Urls.TrackSprite)
end

local function show_element()
	Entity.show_sprite(Urls.Bar)
	Entity.show_sprite(Urls.TrackSprite)
end

local function cancel_fades()
	go.cancel_animations(Urls.Bar, "tint.w")
	go.cancel_animations(Urls.TrackSprite, "tint.w")
end

local function set_progress(self, progress)
	progress = Math.clamp(progress, 0, 1)

	local track_start_x = self.origin_track_position.x
	local track_end_x = -self.origin_track_position.x
	go.set(Urls.Track, "position.x", track_start_x + (track_end_x - track_start_x) * progress)
end

local FADE_Y_VALUE = 10

local function on_show_element(self, message)
	cancel_fades()

	-- self.end_position = go.get_position()

	go.set(".", "position.y", self.end_position.y + FADE_Y_VALUE)
	go.animate(".", "position.y", go.PLAYBACK_ONCE_FORWARD, self.end_position.y, go.EASING_OUTQUAD, 0.3)

	go.animate(Urls.Bar, "tint.w", go.PLAYBACK_ONCE_FORWARD, 1, go.EASING_OUTQUAD, 0.3)
	go.animate(Urls.TrackSprite, "tint.w", go.PLAYBACK_ONCE_FORWARD, 1, go.EASING_OUTQUAD, 0.3)
end

local function on_hide_element(self, message)
	cancel_fades()

	if message.animated then
		go.animate(".", "position.y", go.PLAYBACK_ONCE_FORWARD, self.end_position.y + FADE_Y_VALUE, go.EASING_OUTQUAD, 0.3)
		go.animate(Urls.Bar, "tint.w", go.PLAYBACK_ONCE_FORWARD, 0, go.EASING_OUTQUAD, 0.3)
		go.animate(Urls.TrackSprite, "tint.w", go.PLAYBACK_ONCE_FORWARD, 0, go.EASING_OUTQUAD, 0.3)
	else
		hide_element()
	end
end

function init(self)
	self.origin_track_position = go.get_position(Urls.Track)
	self.end_position = go.get_position()

	set_progress(self, 0)
	hide_element()
end

local function on_update_recharge_progress(self, message)
	set_progress(self, message.progress)
end

function on_message(self, message_id, message, sender)
	if message_id == Msg.SHOW_ELEMENT then
		on_show_element(self, message)
	elseif message_id == Msg.HIDE_ELEMENT then
		on_hide_element(self, message)
	elseif message_id == Msg.Player.UPDATE_RECHARGE_PROGRESS then
		on_update_recharge_progress(self, message)
	end
end
